name: Test Plugin

on:
  pull_request:
    branches:
      - main

jobs:

  lint:
    name: PHP Syntax Check
    uses: tarosky/workflows/.github/workflows/phpcs.yml@main
    with:
      version: 7.4

  assets:
    name: Assets Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install NPM Packages
        run: npm install

      - name: Check JS & CSS syntax
        run: npm run lint

      - name: Build Succeed
        run: npm run build

  short-open-tag:
    name: Short Open Tag Check
    uses: tarosky/workflows/.github/workflows/php-short-open-tag.yml@main

  phpunit:
    name: PHPUnit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install NPM Packages
        run: npm install

      - name: Setup PHP with composer v2
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          tools: composer

      - name: Install Composer Dependencies
        run: composer install

      - name: Start wp-env
        run: npx wp-env start

      - name: Run Tests
        run: npm test

  status-check:
    name: Status Check
    runs-on: ubuntu-latest
    needs: [ short-open-tag, lint, assets, phpunit ]
    if: always()
    steps:
      - uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
